// @ts-expect-error Generated by the OpenNext Cloudflare build before bundling this entrypoint.
import nextHandler from "./.open-next/worker.js";

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
};

type WorkerEnvironment = Record<string, unknown> & {
  PUSH_CRON_SECRET?: string;
};

type NextWorkerHandler = {
  fetch(request: Request, env: WorkerEnvironment, ctx: WorkerContext): Promise<Response>;
};

const handler = nextHandler as NextWorkerHandler;

const worker = {
  fetch: handler.fetch,

  async scheduled(_event: unknown, env: WorkerEnvironment, ctx: WorkerContext) {
    if (!env.PUSH_CRON_SECRET || env.PUSH_CRON_SECRET.length < 32) {
      throw new Error("PUSH_CRON_SECRET is not configured.");
    }
    const response = await handler.fetch(
      new Request("https://ipillgood.internal/api/push/dispatch", {
        method: "POST",
        headers: { "x-ipillgood-cron-secret": env.PUSH_CRON_SECRET },
      }),
      env,
      ctx,
    );
    if (!response.ok) {
      const body = (await response.text()).slice(0, 500);
      throw new Error(`Medication reminder dispatch failed: HTTP ${response.status} ${body}`);
    }
  },
};

export default worker;

// @ts-expect-error Generated exports are available after the OpenNext build.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
