// @ts-expect-error Generated by the OpenNext Cloudflare build before bundling this entrypoint.
import nextHandler from "./.open-next/worker.js";

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
};

type WorkerEnvironment = Record<string, unknown> & {
  PUSH_CRON_SECRET?: string;
};

type ScheduledEvent = {
  scheduledTime?: number;
};

type NextWorkerHandler = {
  fetch(request: Request, env: WorkerEnvironment, ctx: WorkerContext): Promise<Response>;
};

const handler = nextHandler as NextWorkerHandler;
const ACCOUNT_CLEANUP_INTERVAL_MINUTES = 5;
const SESSION_CLEANUP_INTERVAL_MINUTES = 15;
const REMINDER_AUDIT_INTERVAL_MINUTES = 60;

function scheduledPaths(scheduledTime: number) {
  const minute = Math.floor(scheduledTime / 60_000);
  const paths = minute % ACCOUNT_CLEANUP_INTERVAL_MINUTES === 0 ? ["/api/account/deletion/cleanup"] : [];
  if (minute % SESSION_CLEANUP_INTERVAL_MINUTES === 0) {
    paths.push("/api/demo/cleanup", "/api/auth/connection/cleanup");
  }
  paths.push(minute % REMINDER_AUDIT_INTERVAL_MINUTES === 0 ? "/api/push/dispatch?audit=1" : "/api/push/dispatch");
  return paths;
}

async function callScheduledRoute(
  path: string,
  env: WorkerEnvironment,
  ctx: WorkerContext,
) {
  const response = await handler.fetch(
    new Request(`https://ipillgood.internal${path}`, {
      method: "POST",
      headers: { "x-ipillgood-cron-secret": env.PUSH_CRON_SECRET as string },
    }),
    env,
    ctx,
  );
  if (!response.ok) {
    const body = (await response.text()).slice(0, 500);
    throw new Error(`${path} failed: HTTP ${response.status} ${body}`);
  }
}

const worker = {
  fetch: handler.fetch,

  async scheduled(event: ScheduledEvent, env: WorkerEnvironment, ctx: WorkerContext) {
    if (!env.PUSH_CRON_SECRET || env.PUSH_CRON_SECRET.length < 32) {
      throw new Error("PUSH_CRON_SECRET is not configured.");
    }
    const failures: unknown[] = [];
    const scheduledTime = Number.isFinite(event.scheduledTime) ? event.scheduledTime! : Date.now();
    for (const path of scheduledPaths(scheduledTime)) {
      try {
        await callScheduledRoute(path, env, ctx);
      } catch (error) {
        failures.push(error);
      }
    }
    if (failures.length) {
      throw new AggregateError(failures, "One or more scheduled jobs failed.");
    }
  },
};

export default worker;

// @ts-expect-error Generated exports are available after the OpenNext build.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
